language: python
python:
    - "2.6"
    - "2.7"

install:
    - python setup.py develop
    - pip install --allow-all-external django-evolution
    - pip install kgb

script:
    - python ./tests/runtests.py
